This notebook shows how the lower top_X mids files can be derived from the top_50 filenames 
and the HDF5 file containing the data.
Since the lower numbers are subsets of top_50, the filenames can be filtered and matching 
labels need to be generated. The log-melspectrograms are all already contained.

In [1]:
import h5py
import torch
import numpy as np

import utils.utility_funcs as my_funcs

In [33]:
# Paths to the pckl dicts and the valid filenames for 30 mids
PATH_TO_AS_EVAL_30_LABELS = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\pickle_objects\audioset_eval_labels_30_dict.pckl'
PATH_TO_AS_TRAIN_30_LABELS = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\pickle_objects\audioset_train_labels_30_dict.pckl'
PATH_TO_FSD50K_EVAL_30_LABELS = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\pickle_objects\fsd50k_eval_labels_30_dict.pckl'
PATH_TO_FSD50K_TRAIN_30_LABELS = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\pickle_objects\fsd50k_train_labels_30_dict.pckl'

PATH_TO_AS_FNAMES_EVAL_30 = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\audioset_eval_filenames_top30.txt'
PATH_TO_AS_FNAMES_TRAIN_30 = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\audioset_train_filenames_top30.txt'
PATH_TO_FSD50K_FNAMES_EVAL_30 = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\fsd50k_eval_filenames_top30.txt'
PATH_TO_FSD50K_FNAMES_TRAIN_30 = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\fsd50k_train_filenames_top30.txt'

PATH_TO_DATA_HDF5 = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\Audioset_data_cl.hdf5'

In [5]:
# Read in desired filenames
valid_filenames_as_train_30 = my_funcs.read_in_valid_filenames(PATH_TO_AS_FNAMES_TRAIN_30)
valid_filenames_as_eval_30 = my_funcs.read_in_valid_filenames(PATH_TO_AS_FNAMES_EVAL_30)

valid_filenames_fsd50k_train_30 = my_funcs.read_in_valid_filenames(PATH_TO_FSD50K_FNAMES_TRAIN_30)
valid_filenames_fsd50k_eval_30 = my_funcs.read_in_valid_filenames(PATH_TO_FSD50K_FNAMES_EVAL_30)

valid_filenames_fsd50k_eval_30

{'385978',
 '364993',
 '171686',
 '236291',
 '113614',
 '429494',
 '45810',
 '330848',
 '325888',
 '83915',
 '418165',
 '238228',
 '203776',
 '102563',
 '390270',
 '60933',
 '254982',
 '352638',
 '59462',
 '33563',
 '424817',
 '117606',
 '219303',
 '189460',
 '390188',
 '407691',
 '175141',
 '429422',
 '332932',
 '249320',
 '387992',
 '347967',
 '350619',
 '170883',
 '215935',
 '223610',
 '53401',
 '400076',
 '376482',
 '412820',
 '154374',
 '19648',
 '184663',
 '366576',
 '156510',
 '153056',
 '348309',
 '115126',
 '415202',
 '76676',
 '231963',
 '116390',
 '119443',
 '316849',
 '424295',
 '393694',
 '170880',
 '37794',
 '182854',
 '72560',
 '99580',
 '48294',
 '47050',
 '416911',
 '44476',
 '403295',
 '118772',
 '321785',
 '408804',
 '406843',
 '107188',
 '166029',
 '38486',
 '242932',
 '335391',
 '182507',
 '212691',
 '338168',
 '211872',
 '60917',
 '35521',
 '420830',
 '87059',
 '67305',
 '362281',
 '339687',
 '100265',
 '406504',
 '328842',
 '321706',
 '2526',
 '328846',
 '261167'

In [6]:
# Get dicts
audioset_train_labels_30 = my_funcs.pickle_load(PATH_TO_AS_TRAIN_30_LABELS)
audioset_eval_labels_30 = my_funcs.pickle_load(PATH_TO_AS_EVAL_30_LABELS)

fsd50k_train_labels_30 = my_funcs.pickle_load(PATH_TO_FSD50K_TRAIN_30_LABELS)
fsd50k_eval_labels_30 = my_funcs.pickle_load(PATH_TO_FSD50K_EVAL_30_LABELS)

fsd50k_eval_labels_30

{'37199': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '175151': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '253463': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '329838': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '1277': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '30149': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '331398': [0,
  0,
  0,
  0,
  0,
  0

In [ ]:

# For Audioset. Some differences in filenames between audiofiles and metafiles

with h5py.File(PATH_TO_DATA_HDF5, 'a') as data_hdf5:
    as_train_50_grp = data_hdf5['audioset_strong_train_50']
    as_eval_50_grp = data_hdf5['audioset_strong_eval_50']
    as_grps = [as_train_50_grp, as_eval_50_grp]

    fsd50k_train_50_grp = data_hdf5['fsd50k_train_50']
    fsd50k_eval_50_grp = data_hdf5['fsd50k_eval_50']

    print(as_train_50_grp)
    print(as_eval_50_grp)
    print(fsd50k_train_50_grp)
    print(fsd50k_eval_50_grp)
    for as_grp in as_grps:
        
        split_type = as_grp.name.split('_')[-2]
        print(split_type)
        valid_fnames = ""
        labels = ""

        if split_type == 'train':
            valid_fnames = valid_filenames_as_train_30
            labels = audioset_train_labels_30
        else: #eval
            valid_fnames = valid_filenames_as_eval_30
            labels = audioset_eval_labels_30

        for fname in as_grp.keys():

            fname_wo_Y = fname[1::] # Remove leading Y
            nr_of_classes = str(30) 
            membership_attr = 'in_' + nr_of_classes
            label_attr = 'label_' + nr_of_classes
            
            if fname in valid_fnames:
                # Add two attributes: if the dataset is a part of lower classes
                # and the matching label

                as_grp[fname].attrs[membership_attr] = 1 # True
                as_grp[fname].attrs[label_attr] = labels[fname_wo_Y]
                
            else:
                as_grp[fname].attrs[membership_attr] = 0 # False


# Read through the desired group and the dataset names inside
# Compare names to the valid filename list and copy to a new group
# without label info and insert appropriate label info

<HDF5 group "/audioset_strong_train_50" (81070 members)>
<HDF5 group "/audioset_strong_eval_50" (14242 members)>
<HDF5 group "/fsd50k_train_50" (37686 members)>
<HDF5 group "/fsd50k_eval_50" (11185 members)>
train
eval


In [38]:
# The same as above but for FSD50k. FSD50k has varying length audiofiles
# which were processed into 10 sec chunks leading to filenames in the hdf5 being 
# slightly different (an additional '_x', where x: {0, 1, 2}, suffix to identify it) when compared to 
# valid filenames.

with h5py.File(PATH_TO_DATA_HDF5, 'a') as data_hdf5:

    fsd50k_train_50_grp = data_hdf5['fsd50k_train_50']
    fsd50k_eval_50_grp = data_hdf5['fsd50k_eval_50']
    fsd50k_grps = [fsd50k_train_50_grp, fsd50k_eval_50_grp]

    print(fsd50k_train_50_grp)
    print(fsd50k_eval_50_grp)

    for fsd50k_grp in fsd50k_grps:
        
        split_type = fsd50k_grp.name.split('_')[-2]
        valid_fnames = ""
        labels = ""

        if split_type == 'train':
            valid_fnames = valid_filenames_fsd50k_train_30
            labels = fsd50k_train_labels_30
        else: #eval
            valid_fnames = valid_filenames_fsd50k_eval_30
            labels = fsd50k_eval_labels_30

        for fname in fsd50k_grp.keys():

            fname_og = ""
            if '_' in fname:
                fname_og = fname.split('_')[0]
            else:
                fname_og = fname

            nr_of_classes = str(30) 
            membership_attr = 'in_' + nr_of_classes
            label_attr = 'label_' + nr_of_classes
            
            if fname_og in valid_fnames:
                # Add two attributes: if the dataset is a part of lower classes
                # and the matching label

                fsd50k_grp[fname].attrs[membership_attr] = 1 # True
                fsd50k_grp[fname].attrs[label_attr] = labels[fname_og]
                
            else:
                fsd50k_grp[fname].attrs[membership_attr] = 0 # False

<HDF5 group "/fsd50k_train_50" (37686 members)>
<HDF5 group "/fsd50k_eval_50" (11185 members)>


In [40]:
counter = 0
with h5py.File(PATH_TO_DATA_HDF5, 'r') as test:
    print(test.keys())

    as_train_50_grp = test['audioset_strong_train_50']
    as_eval_50_grp = test['audioset_strong_eval_50']

    fsd50k_train_50_grp = test['fsd50k_train_50']
    fsd50k_eval_50_grp = test['fsd50k_eval_50']

    for fname in fsd50k_train_50_grp.keys():
        print(fsd50k_train_50_grp[fname])
        print(fsd50k_train_50_grp[fname].attrs['label'])
        print(fsd50k_train_50_grp[fname].attrs.keys())
        print(fsd50k_train_50_grp[fname].attrs['in_30'])
        if fsd50k_train_50_grp[fname].attrs['in_30'] == 1:
            print(fsd50k_train_50_grp[fname].attrs['label_30'])
        
        if counter == 100:
            break
        counter += 1

<KeysViewHDF5 ['audioset_strong_eval_50', 'audioset_strong_train_50', 'fsd50k_eval_50', 'fsd50k_train_50']>
<HDF5 dataset "10000": shape (1, 1001, 64), type "<f4">
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0]
<KeysViewHDF5 ['in_30', 'label', 'label_30']>
1
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
<HDF5 dataset "100005": shape (1, 1001, 64), type "<f4">
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
<KeysViewHDF5 ['in_30', 'label', 'label_30']>
1
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<HDF5 dataset "100006": shape (1, 1001, 64), type "<f4">
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
<KeysViewHDF5 ['in_30', 'label', 'label_30']>
1
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<HDF5 dataset "100007": shape (1, 1001, 64), type "<f4">
[0 0 0 0 0 0 0 0 0 0 0 0 0

In [29]:
print('Y--12UOziMF0' in valid_filenames_as_train_30)
print('Y--24LG2mr-Y' in valid_filenames_as_train_30)
print('--12UOziMf0' in audioset_train_labels_30)
print('--24LG2mr-Y' in audioset_train_labels_30)

False
True
False
True
